name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  arm64-linux-debug:
    runs-on: [ARM64]
    steps:
      - name: checkout
        uses: https://github.com/actions/checkout@v4
      - name: Build and Test
        run: sh ci/arm64-linux-debug-tests.sh

  x86_64-linux-debug:
    runs-on: [x64-linux]
    steps:
      - name: checkout
        uses: https://github.com/actions/checkout@v4
      - name: Build and Test
        run: sh ci/x86_64-linux-debug-tests.sh