# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

permissions:
  # Sets permission policy for `GITHUB_TOKEN`
  contents: read

jobs:
  arm64-linux-debug:
    timeout-minutes: 420
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Test
        run: sh ci/arm64-linux-debug.sh
  x86_64-linux-debug:
    timeout-minutes: 420
    runs-on: [ubuntu-latest, Linux, x86_64]
    steps:
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2.0.5
        with:
            version: "18.1.2"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull changes
        run: git fetch --unshallow || true && git fetch --tags && git clean -fd
      - name: Build
        run: cmake -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=On && make -C build
      - name: Test
        run: cd build && ctest -C $BUILD_TYPE --output-on-failure